"use strict";
exports.__esModule = true;
var express_1 = require("express");
var suppliers_route_1 = require("./suppliers.route");
var customers_route_1 = require("./customers.route");
var products_route_1 = require("./products.route");
var orders_route_1 = require("./orders.route");
var employees_route_1 = require("./employees.route");
var search_controller_1 = require("../controllers/search.controller");
var router = express_1["default"].Router();
router.use('/suppliers', suppliers_route_1["default"]);
router.use('/products', products_route_1["default"]);
router.use('/orders', orders_route_1["default"]);
router.use('/employees', employees_route_1["default"]);
router.use('/customers', customers_route_1["default"]);
router.get('/search', search_controller_1["default"].search);
exports["default"] = router;
